Banana
TANGEJ0411/git-workshop pull request #3
Opened 2022-11-19 09:36 UTC by TANGEJ0411

拜託拜託
8T8T

2022-11-19 09:39 UTC, Lu-PY reviewed
banana只有一個H1

2022-11-19 09:39 UTC, Lu-PY commented on banana.html
> +    <title>Document</title>
banana呢

2022-11-19 09:39 UTC, Lu-PY commented on banana.html
> +    <h1>banana</h1>
原來在這阿 使用者體驗差評X

2022-11-19 09:44 UTC, Echelon0815 commented on about.html
> +    <h1>about</h1>
第一個字大寫

2022-11-19 09:44 UTC, Echelon0815 commented on banana.html
> +<head>
測試一下

2022-11-19 09:46 UTC, Echelon0815 approved these changes
測試一下二

2022-11-19 09:47 UTC, Echelon0815 requested changes
再改一下好嗎

2022-11-20 05:42 UTC, linjerry777 commented on about.html
> +    <h1>about</h1>
還敢不大寫啊冰鳥

2022-11-21 09:38 UTC, Echelon0815 approved these changes
ok了

2022-11-23 03:06 UTC, TANGEJ0411 commented on banana.html
> +    <title>Document</title>
大家不要這麼火爆＝＝

2022-11-23 03:07 UTC, merged